pipeline {
    agent {
        docker { image 'docker:latest' }
    }
    
    stages {
        stage('Run Apache Server') {
            steps {
                script {
                    // Run Docker container with Apache server
                    sh '''
                        docker run -d -p 80:81 --name my-apache-container httpd:alpine
                    '''
                }
            }
        }
    }
