pipeline {
  agent {
    docker { image 'nginx:1.26.0-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx --version'
      }
    }
  }
  post {
    always {
      sh 'sleep infinity'
    }
  }
}
